#!/bin/bash
# protect-generated-artifacts.sh — PreToolUse hook
# Blocks direct edits to pipeline-generated files.
# These should only be modified by running the correct phase skill.

INPUT=$(cat)
FILE_PATH=$(python -c "import sys,json; print(json.load(sys.stdin).get('tool_input',{}).get('file_path',''))" <<< "$INPUT" 2>/dev/null)

# Nothing to check if no file path
[ -z "$FILE_PATH" ] && exit 0

# Protected patterns: pipeline-generated artifacts
case "$FILE_PATH" in
  */audio/voice.json)
    echo "BLOCKED: audio/voice.json is generated by ingest-voice. Re-run that phase instead of editing directly." >&2
    exit 2 ;;
  */audio/beat-map.json)
    echo "BLOCKED: audio/beat-map.json is generated by ingest-voice. Re-run that phase instead of editing directly." >&2
    exit 2 ;;
  */output/qa_report.json)
    echo "BLOCKED: qa_report.json is generated by qa-reel. Re-run QA instead of editing the report." >&2
    exit 2 ;;
  */output/qa-report.md)
    echo "BLOCKED: qa-report.md is generated by qa-reel. Re-run QA instead of editing the report." >&2
    exit 2 ;;
  *)
    exit 0 ;;
esac
